package com.gsj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserid(Integer userid) {
		set("userid", userid);
	}
	
	public Integer getUserid() {
		return getInt("userid");
	}

	public void setUsername(String username) {
		set("username", username);
	}
	
	public String getUsername() {
		return getStr("username");
	}

	public void setPassword(String password) {
		set("password", password);
	}
	
	public String getPassword() {
		return getStr("password");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setSex(String sex) {
		set("sex", sex);
	}
	
	public String getSex() {
		return getStr("sex");
	}

	public void setNumber(Integer number) {
		set("number", number);
	}
	
	public Integer getNumber() {
		return getInt("number");
	}

	public void setPosition(String position) {
		set("position", position);
	}
	
	public String getPosition() {
		return getStr("position");
	}

	public void setTel(String tel) {
		set("tel", tel);
	}
	
	public String getTel() {
		return getStr("tel");
	}

	public void setEmail(String email) {
		set("email", email);
	}
	
	public String getEmail() {
		return getStr("email");
	}

	public void setType(String type) {
		set("type", type);
	}
	
	public String getType() {
		return getStr("type");
	}

}
