package com.gsj.model;


import com.gsj.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
  public  static  User me = new User();
}
